 FROM node:12 AS base
WORKDIR /app
EXPOSE 3000
EXPOSE 44370

FROM node:12 AS build
WORKDIR /app
RUN npm install -g npm
COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . .
RUN npm run build

FROM base AS final
WORKDIR /app
COPY --from=build /app .
CMD [ "npm", "start" ]
