FROM node:12

# Set working directory
WORKDIR /app

# Update NPM...
RUN npm install -g npm

# Installing dependencies
COPY package*.json /app/
RUN npm install

# Copying source files
COPY . /app

# Building application
RUN npm run build

# Run the app
EXPOSE 44370
CMD [ "npm" "start" ]
