version: '2'
services:
  
  frontend:
    image: zenglobal/im-access-identitymanager-frontend:latest
    links:
      - "backend:graphqlapi"
    ports:
      - "3000:3000"
      - "44370:44370"
    networks:
      backend_net:
      frontend_net:
        ipv4_address: 172.19.0.10
    environment:
      - GRAPHQI_URI=https://graphqlapi:44344/graphql
      - SERVER_HOST=www.identitymanager.local
      - SERVER_PORT_HTTP=3000
      - SERVER_PORT_HTTPS=44370
      - SSL_CERT_PFXFILE=identitymanager.pfx
      - SSL_CERT_PASSPHRASE=${FRONTEND_SSL_PASSPHRASE}
      - COOKIE_SECRET=${FRONTEND_COOKIE_SECRET}
      - MONGO_URI=
      - IDENTITY_URL=${IDENTITYSERVER_URL}
      - IDENTITY_CLIENT_ID=ImAccessGraph
      - IDENTITY_CLIENT_SECRET=${FRONTEND_OIDC_CLIENT_SECRET}
      - GOOGLE_TRACKING_ID=
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - BUILD_ID=1.0.0

  backend:
    image: zenglobal/im-access-graph-backend:latest
    networks:
      - backend_net
    environment:
      - IdentityServer=${IDENTITYSERVER_URL}

networks:
  frontend_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1
  backend_net:
